language: node_js
node_js:
- lts/*
script:
- npx noflo-cache-preheat
- npm run build
- npm test
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: J2EubJi5EJpVFx64OEgFpMuhOFfu2ANRnTUZQMki75vpRfuHN+7ebicTktTMvOA/89FQPssx4ikbOrhIu2/bylFrlTi6fom5XAN8K+iO7pZuep3PMjzEQqL8U0gpfylP412IL9oZEuev7qcLDZgF2ONFXh8vmciGCaFNXdd4SolvReszL9NzZNLNreMc9RkFN4QbGNLlGAaolAfuZyHrn0brQOMHHfTBVoZlnPvWn9zK9VndW6vtWlH3mqDk++wZyZFe41BuVAvl8Zxw1xsFzzu83y/WVE1qJ1Pokni1B5ATYiBKSnAUCldgxg9DrfDlm3RV++Y1xJJE4E46CfXprSfarBZtXiOvBTsf84XWBBbjN4AY9CAtGcMMgdCPBfu7DVGaiAnqTL1rHeGFyPiTrX+Hb1iSNqB5C7uAqn+VTBppYx539L04mWS82ajHwZXtfxbJecVmF3YbiL9JUOP6Nhyhd6D34q2rrArsVU/URLf0wMH2nAQjvEQHi0uX5vTJJ6NQ0KMQ3gZ7EtsXA1mvksLS8+Tbfw1GBl3VFYh/kvEFXfTcMeVdU4epNjaStVLFawQHVIoKHyEJCIXbtxFVPNMyX5wky5pRUqN5ZFXiI2OFZRDxIJU+oSo5GafIMWQ0aTvGitkr1rWBt8cpTqrMi5erFjmcehzFp7ox37K9cSU=
  on:
    tags: true
    repo: noflo/noflo-runtime-headless
